-- Add verb aspect information (perfect/imperfect/imperative) to verbs in surahs 97-114-- Source: quran-morphology.txt-- Extracted from PERF/IMPF/IMPV codes in morphology features-- PERF = perfect (past tense, completed action)-- IMPF = imperfect (present/future tense, ongoing or incomplete action)-- IMPV = imperative (command form)-- Generated: 2025-12-07

-- ========== SURAH 97 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 97 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 97 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 97 AND v.verse_number = 4) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 98 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 1) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 1) AND word_position = 11 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 2) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 4) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 4) AND word_position = 10 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 5) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 5) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 5) AND word_position = 10 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 5) AND word_position = 12 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 6) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 7) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 7) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 8) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 8) AND word_position = 13 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 8) AND word_position = 16 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 98 AND v.verse_number = 8) AND word_position = 20 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 99 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 2) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 5) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 6) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 6) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 7) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 7) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 8) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 99 AND v.verse_number = 8) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 100 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 100 AND v.verse_number = 4) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 100 AND v.verse_number = 5) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 100 AND v.verse_number = 9) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 100 AND v.verse_number = 9) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 100 AND v.verse_number = 10) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 101 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 3) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 5) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 6) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 8) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 101 AND v.verse_number = 10) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 102 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 3) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 4) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 5) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 6) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 7) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 102 AND v.verse_number = 8) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 103 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 103 AND v.verse_number = 3) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 103 AND v.verse_number = 3) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 103 AND v.verse_number = 3) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 103 AND v.verse_number = 3) AND word_position = 8 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 104 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 2) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 3) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 5) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 104 AND v.verse_number = 7) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 105 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 1) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 4) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 105 AND v.verse_number = 5) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 106 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 106 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 106 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 106 AND v.verse_number = 4) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 107 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 1) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 2) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 3) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 6) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 107 AND v.verse_number = 7) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 108 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 108 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 108 AND v.verse_number = 2) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 108 AND v.verse_number = 2) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 109 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 2) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 3) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 4) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 109 AND v.verse_number = 5) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 110 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 2) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 2) AND word_position = 3 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 3) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 110 AND v.verse_number = 3) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 111 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 111 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 111 AND v.verse_number = 1) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 111 AND v.verse_number = 2) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 111 AND v.verse_number = 2) AND word_position = 6 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 111 AND v.verse_number = 3) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 112 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 112 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 112 AND v.verse_number = 3) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 112 AND v.verse_number = 3) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 112 AND v.verse_number = 4) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 113 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 113 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 113 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 113 AND v.verse_number = 2) AND word_position = 4 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 113 AND v.verse_number = 3) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"perfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 113 AND v.verse_number = 5) AND word_position = 5 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- ========== SURAH 114 ==========
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperative"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 114 AND v.verse_number = 1) AND word_position = 1 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 114 AND v.verse_number = 1) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
UPDATE words SET grammar_info = jsonb_set(COALESCE(grammar_info,'{}'::jsonb),'{aspect}','"imperfect"'::jsonb) WHERE verse_id = (SELECT v.id FROM verses v JOIN surahs s ON v.surah_id = s.id WHERE s.surah_number = 114 AND v.verse_number = 5) AND word_position = 2 AND grammar_info->>'part_of_speech' = 'Verb' AND (grammar_info->>'aspect' IS NULL OR grammar_info->>'aspect' = '');
-- Total verbs updated: 109-- Breakdown: perfect: 53, imperfect: 48, imperative: 8